spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-curly-surf-ayn0kkfv-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rHiD9xSAL5vh

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
